// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Printuesi.Server.Data;

#nullable disable

namespace Printuesi.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428213435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Printuesi.Server.Entities.Clients", b =>
                {
                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NIPT")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nipt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ClientID")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.LabelTemplate", b =>
                {
                    b.Property<Guid>("LabelID")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("date_format");

                    b.Property<int>("ExpiryOffsetMonths")
                        .HasColumnType("integer")
                        .HasColumnName("expiry_offset_months");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_name");

                    b.Property<int>("PaperSize")
                        .HasColumnType("integer")
                        .HasColumnName("paper_size");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_path");

                    b.HasKey("LabelID")
                        .HasName("pk_label_templates");

                    b.HasIndex("ClientID")
                        .HasDatabaseName("ix_label_templates_client_id");

                    b.ToTable("label_templates", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobObjects", b =>
                {
                    b.Property<Guid>("PrintJobObjectID")
                        .HasColumnType("uuid")
                        .HasColumnName("print_job_object_id");

                    b.Property<string>("Expiry_Date")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("LabelID")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<string>("Lot_Num")
                        .HasColumnType("text")
                        .HasColumnName("lot_num");

                    b.Property<Guid>("PrintJobID")
                        .HasColumnType("uuid")
                        .HasColumnName("print_job_id");

                    b.Property<int>("Quantity_Printed")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_printed");

                    b.Property<int>("Quantity_Requested")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_requested");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("PrintJobObjectID")
                        .HasName("pk_print_job_objects");

                    b.HasIndex("LabelID")
                        .HasDatabaseName("ix_print_job_objects_label_id");

                    b.HasIndex("PrintJobID")
                        .HasDatabaseName("ix_print_job_objects_print_job_id");

                    b.ToTable("print_job_objects", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.Property<Guid>("PrintJobID")
                        .HasColumnType("uuid")
                        .HasColumnName("print_job_id");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("PrintJobID")
                        .HasName("pk_print_jobs");

                    b.HasIndex("ClientID")
                        .HasDatabaseName("ix_print_jobs_client_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_print_jobs_created_by");

                    b.ToTable("print_jobs", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Supplies", b =>
                {
                    b.Property<Guid>("SupplyID")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_id");

                    b.Property<DateOnly>("Added")
                        .HasColumnType("date")
                        .HasColumnName("added");

                    b.Property<float>("Quantity")
                        .HasColumnType("real")
                        .HasColumnName("quantity");

                    b.Property<int>("SupplyType")
                        .HasColumnType("integer")
                        .HasColumnName("supply_type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("SupplyID")
                        .HasName("pk_supplies");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.SupplyUsageLogs", b =>
                {
                    b.Property<Guid>("SupplyUsageLogID")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_usage_log_id");

                    b.Property<Guid>("PrintJobID")
                        .HasColumnType("uuid")
                        .HasColumnName("print_job_id");

                    b.Property<Guid>("SupplyID")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_id");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<float>("UsedQuantity")
                        .HasColumnType("real")
                        .HasColumnName("used_quantity");

                    b.HasKey("SupplyUsageLogID")
                        .HasName("pk_supply_usage_logs");

                    b.HasIndex("PrintJobID")
                        .HasDatabaseName("ix_supply_usage_logs_print_job_id");

                    b.HasIndex("SupplyID")
                        .HasDatabaseName("ix_supply_usage_logs_supply_id");

                    b.ToTable("supply_usage_logs", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Users", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserID")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Printuesi.Server.Entities.LabelTemplate", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.Clients", "Clients")
                        .WithMany("LabelTemplate")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_label_templates_clients_client_id");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobObjects", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.LabelTemplate", "LabelTemplate")
                        .WithMany()
                        .HasForeignKey("LabelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_print_job_objects_label_templates_label_id");

                    b.HasOne("Printuesi.Server.Entities.PrintJobs", "PrintJob")
                        .WithMany("PrintJobObjects")
                        .HasForeignKey("PrintJobID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_print_job_objects_print_jobs_print_job_id");

                    b.Navigation("LabelTemplate");

                    b.Navigation("PrintJob");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.Clients", "Client")
                        .WithMany("PrintJobs")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_print_jobs_clients_client_id");

                    b.HasOne("Printuesi.Server.Entities.Users", "User")
                        .WithMany("PrintJobs")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_print_jobs_users_created_by");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.SupplyUsageLogs", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.PrintJobs", "PrintJob")
                        .WithMany()
                        .HasForeignKey("PrintJobID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_supply_usage_logs_print_jobs_print_job_id");

                    b.HasOne("Printuesi.Server.Entities.Supplies", "Supply")
                        .WithMany("UsageLogs")
                        .HasForeignKey("SupplyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_supply_usage_logs_supplies_supply_id");

                    b.Navigation("PrintJob");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Clients", b =>
                {
                    b.Navigation("LabelTemplate");

                    b.Navigation("PrintJobs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.Navigation("PrintJobObjects");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Supplies", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Users", b =>
                {
                    b.Navigation("PrintJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
