// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Printuesi.Server.Data;

#nullable disable

namespace Printuesi.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423193655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Printuesi.Server.Entities.Clients", b =>
                {
                    b.Property<string>("Client_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("NIPT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Client_ID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.LabelTemplate", b =>
                {
                    b.Property<string>("Label_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Client_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Date_Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Expiry_Offset_Months")
                        .HasColumnType("int");

                    b.Property<string>("Label_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaperSize")
                        .HasColumnType("int");

                    b.Property<string>("Pdf_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Label_ID");

                    b.HasIndex("Client_ID");

                    b.ToTable("LabelTemplates");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobObjects", b =>
                {
                    b.Property<string>("PrintJobObject_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Expiry_Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lot_Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintJob_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity_Printed")
                        .HasColumnType("int");

                    b.Property<int>("Quantity_Requested")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PrintJobObject_ID");

                    b.HasIndex("Label_ID");

                    b.HasIndex("PrintJob_ID");

                    b.ToTable("PrintJobObjects");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.Property<string>("PrintJob_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Client_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Completed_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PrintJob_ID");

                    b.HasIndex("Client_ID");

                    b.HasIndex("Created_By");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Supplies", b =>
                {
                    b.Property<string>("Supply_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Added")
                        .HasColumnType("date");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<int>("SupplyType")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Supply_ID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.SupplyUsageLogs", b =>
                {
                    b.Property<string>("SupplyUsageLog_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PrintJob_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Supply_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Used_At")
                        .HasColumnType("datetime2");

                    b.Property<float>("Used_Quantity")
                        .HasColumnType("real");

                    b.HasKey("SupplyUsageLog_ID");

                    b.HasIndex("PrintJob_ID");

                    b.HasIndex("Supply_ID");

                    b.ToTable("SupplyUsageLogs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Users", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.LabelTemplate", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.Clients", "Clients")
                        .WithMany("LabelTemplate")
                        .HasForeignKey("Client_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobObjects", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.LabelTemplate", "LabelTemplate")
                        .WithMany()
                        .HasForeignKey("Label_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Printuesi.Server.Entities.PrintJobs", "PrintJob")
                        .WithMany("PrintJobObjects")
                        .HasForeignKey("PrintJob_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LabelTemplate");

                    b.Navigation("PrintJob");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.Clients", "Client")
                        .WithMany("PrintJobs")
                        .HasForeignKey("Client_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Printuesi.Server.Entities.Users", "User")
                        .WithMany("PrintJobs")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.SupplyUsageLogs", b =>
                {
                    b.HasOne("Printuesi.Server.Entities.PrintJobs", "PrintJob")
                        .WithMany()
                        .HasForeignKey("PrintJob_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Printuesi.Server.Entities.Supplies", "Supply")
                        .WithMany("UsageLogs")
                        .HasForeignKey("Supply_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PrintJob");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Clients", b =>
                {
                    b.Navigation("LabelTemplate");

                    b.Navigation("PrintJobs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.PrintJobs", b =>
                {
                    b.Navigation("PrintJobObjects");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Supplies", b =>
                {
                    b.Navigation("UsageLogs");
                });

            modelBuilder.Entity("Printuesi.Server.Entities.Users", b =>
                {
                    b.Navigation("PrintJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
